### ISSUE TITLE
Bug in PaxEEmv_V1.00.00_20170401.jar

### ISSUE THREAD

**Issue by saveuighur81** [superqqgto/nimabilalla#3]
Hi Sir,

I convert your program to run on Androd Studio 3.1.4. I found a bug with your programs. I show from the caller function ( Component.transPreDeal(context, transType); ) to the deepest function ( EmvImpl.getInstance(FinancialApplication.mApp).getEmv() ) in PaxEEmv_V1.00.00_20170401.jar.

```
1. # ActionTransPreDeal 
@Override
    protected void process() {

        FinancialApplication.mApp.runInBackground(new Runnable() {
            @Override
            public void run() {
                Context context = ContextUtils.getActyContext();

                ///////////////////////////////////////////////////////////////////////
                // 执行交易预处理
                int ret = Component.transPreDeal(context, transType); // BUG IN HERE
                ///////////////////////////////////////////////////////////////////////

                //这里执行完 transPreDeal 比较耗时，导致界面输完金额进入到刷卡界面会卡2秒
                setResult(new ActionResult(ret, null));   // NEVER EXECUTED
            }
        });

    }

2. # Component
    public static int transPreDeal(final Context context, ETransType transType) {
        // I hide some functions in here to make it easy to see

         ///////////////////////////////////////////////////////////////////////
        // EMV初始化， 交易开始前设置emv配置，capk和aid，减少后面emv处理时间
        EmvTransProcess.getInstance().init();  // BUG  IN HERE
         ///////////////////////////////////////////////////////////////////////

        return ret;  // NEVER EXECUTED
    }


3. # EmvTransProcess.java
public void init() {
         ///////////////////////////////////////////////////////////////////////
         EmvManager.emvInit(); // BUG  IN HERE
         ///////////////////////////////////////////////////////////////////////

        setEmvConfig();   // NEVER EXECUTED
        // I hide some functions in here to make it easy to see
}

4. # EmvManager.java
        // I hide some functions in here to make it easy to see

    private void init() {
        ///////////////////////////////////////////////////////////////////////
        emv = EmvImpl.getInstance(FinancialApplication.mApp).getEmv();  // BUG  IN HERE
         ///////////////////////////////////////////////////////////////////////
    } // NEVER EXECUTED

    public static int emvInit() {
        try {      
            ///////////////////////////////////////////////////////////////////////
            return getEmv().emvInit();   // BUG  IN HERE
            ///////////////////////////////////////////////////////////////////////
        } catch (EmvException e) {
            e.printStackTrace();
        }
        return -1;
    }

5. # EmvImpl.java (in PaxEEmv_V1.00.00_20170401.jar)
public class EmvImpl implements IEmv {
        // I hide some functions in here to make it easy to see

    static {
        System.loadLibrary("SM_Android");
        System.loadLibrary("L2_Common");
        System.loadLibrary("L2_Conv");

        ///////////////////////////////////////////////////////////////////////
        System.loadLibrary("emvCallback");        // BUG  IN HERE (FREEZE)
        ///////////////////////////////////////////////////////////////////////

        System.loadLibrary("F_DEVICE_LIB_Android_v602");  // NEVER EXECUTED
        System.loadLibrary("F_PUBLIC_LIB_Android_v103");
        System.loadLibrary("F_EMV_LIB_Android_v650");
        System.loadLibrary("F_ENTRY_LIB_Android_v550");
        System.loadLibrary("F_WAVE_LIB_Android_v350");
        System.loadLibrary("F_MC_LIB_Android_v550");
        System.loadLibrary("F_QPBOC_LIB_Android_v350");
        System.loadLibrary("emvtrans");
        appPath = "";
        capkList = new ArrayList();
        aidParamList = new ArrayList();
    }

    private EmvImpl() {
    }

    public static synchronized EmvImpl getInstance(Context context) {
        if (instance == null) {
            instance = new EmvImpl();

            try {
                instance.emvInit();
            } catch (EmvException var2) {
                ;
            }

            appPath = context.getFilesDir().getAbsoluteFile().getPath() + File.separator;
        }

        context = context;
        paxEmvTrans = EmvTrans.getInstance(instance);
        paxEmvDevice = EmvDevice.getInstance(instance);
        paxEmvContactless = EmvContactless.getInstance(instance);
        return instance;
    }

    public IEmv getEmv() {
        return getInstance(context);
    }

```

Steps to find bugs:
1. Login at the beginning of the screen with the **initial password is 000000**
2. Set **Config> Comm> Communication> Demo**
3. I pressed the **Offline button**, an error like this will appear:

**02-01 21:55:52.086 30257-30290/com.pax.edc E/art: dlopen("/data/app/com.pax.edc-1/lib/arm/libemvCallback.so", RTLD_LAZY) failed: dlopen failed: "/data/app/com.pax.edc-1/lib/arm/libemvCallback.so" has no loadable segments**

4. The **bindStateOnAction()** function in the **OfflineSaleTrans.java** is never executed because the program stops at **EmvManager.emvInit()** in **EmvTransProcess.java**;

5. If the **init ()** in **EmvTransProcess.java** is disabled, when I press **the Offline button** then **bindStateOnAction()** will be executed and **activity_bankcard_pay.xml view** will appear.

Completed log in crash folder

> SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@3ffdf13d
versionCode=1
BOARD=msm8909
BOOTLOADER=unknown
TYPE=user
ID=LMY47V
TIME=1500621471000
BRAND=PAX
TAG=Build
SERIAL=08201357XX
HARDWARE=qcom
SUPPORTED_ABIS=[Ljava.lang.String;@30ce7d32
CPU_ABI=armeabi-v7a
RADIO=unknown
IS_DEBUGGABLE=false
MANUFACTURER=PAX
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@232fd294
TAGS=test-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=builder
FINGERPRINT=PAX/CB03/CB03:5.1.1/LMY47V/CB03_CH_V4.70_S:user/test-keys
HOST=pd-sign
PRODUCT=CB03
versionName=1.0-debug
DISPLAY=PayDroid_5.1.1_Aquarius_V02.3.04_20170721
MODEL=A920
DEVICE=CB03
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.pax.edc-2/lib/arm/libemvCallback.so" has no loadable segments
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:988)
	at com.pax.eemv.EmvImpl.<clinit>(EmvImpl.java:33)
	at com.pax.eemv.EmvImpl.getInstance(EmvImpl.java)
	at com.pax.manager.neptune.EmvManager.init(EmvManager.java:44)
	at com.pax.manager.neptune.EmvManager.<init>(EmvManager.java:36)
	at com.pax.manager.neptune.EmvManager.<init>(EmvManager.java:28)
	at com.pax.manager.neptune.EmvManager$LazyHolder.<clinit>(EmvManager.java:32)
	at com.pax.manager.neptune.EmvManager$LazyHolder.access$100(EmvManager.java)
	at com.pax.manager.neptune.EmvManager.getInstance(EmvManager.java:40)
	at com.pax.manager.neptune.EmvManager.getEmv(EmvManager.java:48)
	at com.pax.manager.neptune.EmvManager.emvInit(EmvManager.java:53)
	at com.pax.pay.emv.EmvTransProcess.init(EmvTransProcess.java:75)
	at com.pax.pay.trans.component.Component.transPreDeal(Component.java:83)
	at com.pax.pay.trans.action.ActionTransPreDeal.process(ActionTransPreDeal.java:32)
	at com.pax.abl.core.AAction.execute(AAction.java:27)
	at com.pax.pay.trans.BaseTrans.execute(BaseTrans.java:161)
	at com.pax.view.MenuPage.process(MenuPage.java:162)
	at com.pax.view.MenuPage.access$300(MenuPage.java:29)
	at com.pax.view.MenuPage$1.onItemClick(MenuPage.java:135)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:3876)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3641)
	at android.view.View.dispatchTouchEvent(View.java:8472)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
	at com.pax.view.CustomGridView.dispatchTouchEvent(CustomGridView.java:31)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1720)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2785)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
	at android.view.View.dispatchPointerEvent(View.java:8667)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4141)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4007)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3562)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3615)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3581)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3698)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3589)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3755)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3562)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3615)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3581)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3589)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3562)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5825)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5799)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5770)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5915)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5260)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

How to resolved that problems? Thanks

Best Regards,
Yudha

**Comment by saveuighur81** [comment]
The libemvCallback.so file that is in the jniLibs folder is corrupted. After I copied the original so files from this site, everything was worked.
